# Generated by Django 3.0.2 on 2020-01-13 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_users_company_registeration_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tax', models.IntegerField()),
            ],
            options={
                'db_table': 'ProductTax',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('product_tax', models.BooleanField(default=True)),
                ('supply_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('stock_amount', models.IntegerField(default=999)),
                ('minimum_buying', models.IntegerField(default=1)),
                ('vendorcode', models.CharField(max_length=50)),
                ('delivery_company', models.CharField(default='선우택배', max_length=50)),
                ('delivery_fee', models.IntegerField()),
                ('return_delivery_fee', models.IntegerField()),
                ('start_delivery_address', models.CharField(max_length=200)),
                ('return_delivery_address', models.CharField(max_length=200)),
                ('search_keyword', models.CharField(max_length=200)),
                ('adult_restricted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Categories')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
