# Generated by Django 3.0.2 on 2020-01-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='return_delivery_address_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='start_delivery_address_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
