# Generated by Django 3.0.2 on 2020-01-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200114_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTax',
        ),
    ]
