# Generated by Django 3.0.2 on 2020-01-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_manager_name', models.CharField(max_length=50)),
                ('company_manager_phone_number', models.CharField(max_length=50)),
                ('company_manager_email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CompanyContact',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=50)),
                ('company_registeration_number', models.CharField(max_length=50)),
                ('company_phone_number', models.CharField(max_length=50, null=True)),
                ('representative_name', models.CharField(max_length=50)),
                ('online_distributor_certification_text', models.CharField(max_length=100)),
                ('banking_company', models.CharField(max_length=50)),
                ('banking_number', models.CharField(max_length=50)),
                ('banking_account_name', models.CharField(max_length=50)),
                ('invitation_codes', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comany_contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CompanyContact')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
