# Generated by Django 3.0.2 on 2020-01-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_codes', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Invitation_codes',
            },
        ),
    ]
