# Generated by Django 3.0.2 on 2020-01-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_invitationcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='comany_contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.CompanyContact'),
        ),
        migrations.AlterModelTable(
            name='invitationcodes',
            table='InvitationCodes',
        ),
    ]
