# Generated by Django 3.0.2 on 2020-01-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200112_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='comany_contact_id',
            new_name='company_contact',
        ),
    ]
