# Generated by Django 3.0.2 on 2020-01-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200112_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='company_registeration_image',
            field=models.ImageField(default='default.jpg', upload_to='company_registeration_image'),
        ),
    ]
