# Generated by Django 3.0.2 on 2020-01-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_users_company_registeration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='company_registeration_image',
        ),
    ]
