# Generated by Django 3.0.2 on 2020-01-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200113_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationcodes',
            old_name='invitation_codes',
            new_name='invitation_code',
        ),
    ]
