# Generated by Django 3.0.2 on 2020-01-13 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderer_name', models.CharField(max_length=50)),
                ('orderer_phone_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Orderers',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'OrderStatus',
            },
        ),
        migrations.CreateModel(
            name='Receivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_phone_number', models.CharField(max_length=50)),
                ('receiver_address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Receivers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_memo', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Orderers')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
