# Generated by Django 3.0.2 on 2020-01-13 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        ('user', '0006_users_company_registeration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='receivers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Receivers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users'),
        ),
    ]
