# Generated by Django 3.0.2 on 2020-01-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200113_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='receivers',
            new_name='receiver',
        ),
    ]
